# Generated by Django 5.0.2 on 2024-02-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
