# Generated by Django 5.0.2 on 2024-02-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category/'),
        ),
    ]
